#Hypr Config, open individually one of this files for modify

source = /home/rafael/.config/hypr/modules/animation.conf
source = /home/rafael/.config/hypr/modules/autoStart.conf
source = /home/rafael/.config/hypr/modules/bins.conf
source = /home/rafael/.config/hypr/modules/decorations.conf
source = /home/rafael/.config/hypr/modules/deviceGesture.conf
source = /home/rafael/.config/hypr/modules/dwindle.conf
source = /home/rafael/.config/hypr/modules/enviromentVariables.conf
source = /home/rafael/.config/hypr/modules/input.conf
source = /home/rafael/.config/hypr/modules/lookGeneral.conf
source = /home/rafael/.config/hypr/modules/master.conf
source = /home/rafael/.config/hypr/modules/misc.conf
source = /home/rafael/.config/hypr/modules/monitors.conf
source = /home/rafael/.config/hypr/modules/programsShort.conf
source = /home/rafael/.config/hypr/modules/workspaceWindows.conf
